$(document).ready(function(){
    $("#btn_script").click(function(){
        $("#script").toggle();
    });
    $("#btn_query").click(function(){
        $("#query").toggle();
    });
    $("#btn_class").click(function(){
        $("#class").toggle();
    });
    $("#btn_span").click(function(){
        $("#span").toggle();
    });
    $("#btn_css").click(function(){
        $("#css").toggle();
    });
});